BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        id: entriesBox
        cols: 1
        orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        size_hint_y: 0.2
        Button:
            text: "Create Labels"
            on_release: app.create_widgets()
        Button:
            text: "Clear Labels!"
            on_release: app.clear_all()